#!/usr/bin/env python3
"""Tools that tools/README.md does not list, and entries that name nothing.

    tools/tools_readme_check.py [--write]

WHY

tools/ holds 125 Python sweeps and eight subdirectories, and until 2026-08-27
the only index of any of it was the CHECKS list inside sweep_guard.py - which
names about thirty of them and says nothing about the rest. Someone looking for
"is there already a sweep for this?" had `ls` and the file names.

A hand-written index would answer that question until the next tool was added,
and then answer it wrongly, which is worse: a reader who trusts an index that
has silently dropped four sweeps writes the fifth copy of one of them.

WHAT IT DOES

Regenerates the table in tools/README.md from the tools on disk - each one's
name and the first line of its own docstring - and reports every difference.
The summary is the docstring's, so a tool whose purpose changes updates its own
entry and nothing has to be remembered.

`--write` rewrites the generated block. Everything outside the two markers is
prose and is left alone.

WHAT IT CANNOT SEE

Whether a docstring's first line is any good. It only checks that the README
says what the tool says about itself.
"""
import ast
import re
import sys
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
README = TOOLS / "README.md"

BEGIN = "<!-- generated by tools/tools_readme_check.py; do not edit by hand -->"
END = "<!-- end generated -->"

#: Not sweeps. Kept in step with tools_run_check.py's SKIP, which is the same
#: judgement made for the same reason: these are libraries, generators, and
#: things that open a window.
NOT_A_SWEEP = {
    "framexml_source.py": "library - the FrameXML reader every framexml_* sweep imports",
    "ownership_walk.py": "library - walks who owns which UI element",
    "opcode_map_utils.py": "library - loads and compares the opcode tables",
    "cpp_number.py": "library - reads C++ integer and float literals",
    "gen_opcode_registry.py": "generator - writes the opcode registry source",
    "asset_pipeline_gui.py": "GUI - the asset extraction front end",
    "m2_viewer.py": "GUI - opens an M2 model",
    "upscale_textures.py": "batch job - upscales extracted textures",
    "asset_pack_curate.py": "batch job - audits an asset-pack overlay",
    "sweep_guard.py": "the runner - one CTest entry over the pinned sweeps",
    "tools_run_check.py": "the runner for everything sweep_guard does not run",
    "tools_readme_check.py": "this file",
}


def summary(path):
    """The tool's own first docstring line, or an empty string."""
    try:
        doc = ast.get_docstring(ast.parse(path.read_text(errors="ignore")))
    except (SyntaxError, ValueError, OSError):
        return ""
    return (doc or "").strip().split("\n")[0].strip()


def pinned_in_sweep_guard():
    """The tool names sweep_guard pins a ceiling for."""
    guard = (TOOLS / "sweep_guard.py").read_text(errors="ignore")
    return set(re.findall(r'"([a-z0-9_]+\.py)"', guard))


def rows():
    pinned = pinned_in_sweep_guard()
    out = []
    for path in sorted(TOOLS.glob("*.py")):
        note = NOT_A_SWEEP.get(path.name)
        if note:
            where = note
        elif path.name in pinned:
            where = "pinned by sweep_guard"
        else:
            where = "run by tools_run_check"
        out.append((path.name, summary(path) or "(no docstring)", where))
    return out


def table(entries):
    lines = ["| Tool | What it reports | How it runs |",
             "| --- | --- | --- |"]
    for name, what, where in entries:
        lines.append(f"| `{name}` | {what} | {where} |")
    return "\n".join(lines)


def main():
    entries = rows()
    generated = table(entries)

    if not README.is_file():
        print("0 tool(s) missing from tools/README.md\n")
        print("tools/README.md does not exist; run with --write to create the table")
        return 0

    text = README.read_text()
    if BEGIN not in text or END not in text:
        print(f"{len(entries)} tool(s) missing from tools/README.md\n")
        print("  the generated block markers are gone from tools/README.md")
        return 0

    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    fresh = f"{head}{BEGIN}\n\n{generated}\n\n{END}{tail}"

    if "--write" in sys.argv:
        README.write_text(fresh)
        print("0 tool(s) missing from tools/README.md\n")
        print(f"  wrote {len(entries)} entries")
        return 0

    listed = dict(re.findall(r"^\| `([a-z0-9_]+\.py)` \| (.*?) \|", rest.split(END)[0],
                             re.M))
    wrong = []
    for name, what, _where in entries:
        if name not in listed:
            wrong.append((name, "not listed"))
        elif listed[name] != what:
            wrong.append((name, "listed with a summary its docstring no longer has"))
    for name in listed:
        if not (TOOLS / name).is_file():
            wrong.append((name, "listed and no longer exists"))

    print(f"{len(wrong)} tool(s) missing from tools/README.md\n")
    for name, why in sorted(wrong):
        print(f"  {name:38} {why}")
    if not wrong:
        print("  (none)")
    else:
        print("\n  tools/tools_readme_check.py --write brings the table back in step")
    # The population, which sweep_guard requires: a matcher that stops
    # recognising a table row would otherwise report a clean tree.
    print(f"\n{len(entries)} tool(s) on disk, {len(listed)} listed in the README")
    return 0


if __name__ == "__main__":
    sys.exit(main())
